{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "94d2999c-f613-4e7d-b1eb-c591e82eaa2e",
   "metadata": {},
   "outputs": [],
   "source": [
    "import os\n",
    "import streamlit as st\n",
    "import google.generativeai as genai\n",
    "import PyPDF2\n",
    "\n",
    "# --- This is the \"Engine\" we perfected in the Jupyter Notebook ---\n",
    "def draft_cover_letter_with_gemini(resume, job_desc, template):\n",
    "    \"\"\"Constructs a much more forceful and explicit prompt for Gemini.\"\"\"\n",
    "    prompt = f\"\"\"\n",
    "    You are an expert career coach and professional resume writer. Your task is to draft a world-class cover letter.\n",
    "\n",
    "    **CONTEXT:**\n",
    "\n",
    "    ---RESUME START---\n",
    "    {resume}\n",
    "    ---RESUME END---\n",
    "\n",
    "    ---JOB DESCRIPTION START---\n",
    "    {job_desc}\n",
    "    ---JOB DESCRIPTION END---\n",
    "    \n",
    "    ---COVER LETTER TEMPLATE START---\n",
    "    {template}\n",
    "    ---COVER LETTER TEMPLATE END---\n",
    "\n",
    "    **CRITICAL INSTRUCTIONS:**\n",
    "\n",
    "    1.  **ADHERE TO THE TEMPLATE:** You MUST follow the structure of the provided cover letter template exactly. Use all the specified subheadings and bullet points as formatted in the template.\n",
    "\n",
    "    2.  **SYNTHESIZE, DON'T HALLUCINATE:** Populate the template by extracting and synthesizing information ONLY from the provided resume and job description. Do NOT invent skills or experiences.\n",
    "\n",
    "    3.  **FILL ALL PLACEHOLDERS:** You must fill every placeholder like `[Company Name]` or `[Exact Position Title]`.\n",
    "\n",
    "    4.  **HANDLE MISSING INFORMATION INTELLIGENTLY:**\n",
    "        * If the job description does not mention a specific company mission for the `[Company Mission or Value]` placeholder, you MUST infer a plausible one based on the industry (e.g., \"data-driven decision-making,\" \"technological innovation,\" \"enhancing customer experiences\").\n",
    "        * DO NOT, under any circumstances, output the placeholder text itself.\n",
    "\n",
    "    5.  **POPULATE BULLET POINTS:** For the \"Relevant Skills & Alignment\" and \"Selected Achievements\" sections, you MUST populate the bullet points with specific, concise examples and metrics from the resume.\n",
    "\n",
    "    6.  **FINAL OUTPUT:** The final output should be ONLY the completed cover letter text. Do not include any of your own commentary.\n",
    "    \"\"\"\n",
    "    \n",
    "    model = genai.GenerativeModel('gemini-1.5-flash')\n",
    "    response = model.generate_content(prompt)\n",
    "    return response.text\n",
    "\n",
    "# --- This is the \"Car Body\" - The Streamlit User Interface ---\n",
    "\n",
    "st.set_page_config(page_title=\"AI Cover Letter Assistant\", page_icon=\"✍️\", layout=\"wide\")\n",
    "st.title(\"✍️ AI Cover Letter Assistant\")\n",
    "\n",
    "# IMPORTANT: Configure the API key using Streamlit's secrets management\n",
    "try:\n",
    "    genai.configure(api_key=st.secrets[\"GEMINI_API_KEY\"])\n",
    "except Exception as e:\n",
    "    st.error(\"API Key not configured. The app owner needs to set it in the Streamlit secrets.\")\n",
    "    st.stop()\n",
    "\n",
    "# Use columns for a cleaner layout\n",
    "col1, col2 = st.columns(2)\n",
    "\n",
    "with col1:\n",
    "    st.header(\"1. Your Information\")\n",
    "    uploaded_resume = st.file_uploader(\"Upload Your Resume (PDF)\", type=['pdf'])\n",
    "    \n",
    "    default_template = \"\"\"[Your Name]\n",
    "[Your Street Address]\n",
    "[Your City, State, Zip Code] | [Your Phone Number]\n",
    "[Your Email Address] | [LinkedIn URL]\n",
    "\n",
    "[Date]\n",
    "\n",
    "[Hiring Manager Name]\n",
    "[Hiring Manager Title]\n",
    "[Company Name]\n",
    "[Company Address]\n",
    "\n",
    "Dear [Mr./Ms./Mx. Last Name or Hiring Manager],\n",
    "\n",
    "**Introduction**\n",
    "I am writing to express my interest in the [Exact Position Title] role at [Company Name], as advertised on [Job Board/Company Careers Page]. As a [Your Role, e.g., Master's student in Business Analytics], I bring a blend of technical expertise, business insight, and a passion for [specific company focus or industry]. I am drawn to [Company Name] because of its commitment to [Company Mission or Value].\n",
    "\n",
    "**Professional Snapshot & Value Proposition**\n",
    "[1-2 sentence summary of your value]\n",
    "\n",
    "**Relevant Skills & Alignment with Role**\n",
    "* **Skill 1 Name** – [Description of how you used this skill with examples from your resume].\n",
    "* **Skill 2 Name** – [Description of how you used this skill with examples from your resume].\n",
    "* **Skill 3 Name** – [Description of how you used this skill with examples from your resume].\n",
    "\n",
    "**Selected Achievements**\n",
    "* **Achievement 1** – [Quantifiable achievement from your resume].\n",
    "* **Achievement 2** – [Quantifiable achievement from your resume].\n",
    "\n",
    "**Closing & Call to Action**\n",
    "I am excited about the opportunity to bring my analytical expertise and collaborative approach to [Company Name]. I am confident my blend of technical skills, business acumen, and drive to deliver measurable results align with your team’s goals. Thank you for considering my application, and I look forward to the opportunity to discuss how I can contribute to your success.\n",
    "\n",
    "Sincerely,\n",
    "[Your Full Name]\n",
    "\"\"\"\n",
    "    cover_letter_template = st.text_area(\"Your Cover Letter Template (Edit if needed)\", value=default_template, height=300)\n",
    "\n",
    "with col2:\n",
    "    st.header(\"2. The Job You Want\")\n",
    "    job_description = st.text_area(\"Paste the Full Job Description Here\", height=435)\n",
    "\n",
    "if st.button(\"Generate My Cover Letter\", type=\"primary\", use_container_width=True):\n",
    "    if uploaded_resume and job_description:\n",
    "        with st.spinner(\"Reading your resume...\"):\n",
    "            try:\n",
    "                # Read the uploaded PDF file\n",
    "                pdf_reader = PyPDF2.PdfReader(uploaded_resume)\n",
    "                resume_text = \"\"\n",
    "                for page in pdf_reader.pages:\n",
    "                    resume_text += page.extract_text()\n",
    "            except Exception as e:\n",
    "                st.error(f\"Failed to read PDF: {e}\")\n",
    "                st.stop()\n",
    "        \n",
    "        with st.spinner(\"🧠 AI is drafting your cover letter... This may take a moment.\"):\n",
    "            draft = draft_cover_letter_with_gemini(resume_text, job_description, cover_letter_template)\n",
    "        \n",
    "        st.header(\"✅ Your Draft Is Ready!\")\n",
    "        st.text_area(\"Review and copy your letter below\", value=draft, height=500)\n",
    "    else:\n",
    "        st.warning(\"Please upload your resume and paste the job description first.\")"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.7"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
